import { Metadata } from "next";
export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Suman",
    template: "%s | Next.js -Suman",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          <p>Header</p>
        </header>

        {children}

        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
